# Generated by Django 2.2.5 on 2019-10-31 22:32

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('app_notifpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='audio_aviso',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='audio/'),
        ),
    ]
