# Generated by Django 2.2.5 on 2019-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notifpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='audio_aviso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
