# Generated by Django 2.2.5 on 2019-11-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_notifpi', '0002_aviso_audio_aviso'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aviso',
            table='audio_aviso',
        ),
    ]
